gopinath-langote/1build

README.md
=> 📝 add description and usage examples

.travis.yml, requirements.txt
=> % Add codecov to travis.

README.md
=> % Add codecov badge in readme.

README.md
=> % Add requres.io badge in readme.

docs/pip_publish.md
=> 📝Document creating distribution and publish process.

.travis.yml
=> 🔐 Safety check of dependancies in travis -ci

README.md
Issue: #34
[![Requirements Status](https://img.shields.io/pypi/dm/1build.svg)](https://pypi.org/project/1build)
=> ⑩ show number of downloads in readme.

1build
=> 🍀 refactor - inline if else.

README.md, onebuild/input_parser.py, onebuild/main.py, onebuild/utils.py, tests/test_help_command.py, tests/test_list_command.py
=> List all available command from current project

docs/CHANGELOG.md
=> Add CHANGELOG.md

docs/CHANGELOG.md
=> Release 1.0.0

README.md, onebuild/__init__.py, onebuild/input_parser.py, onebuild/main.py, onebuild/utils.py, setup.py, tests/test_help_command.py, tests/test_version_command.py
added -v and --version cmdline arguments to get current version of 1build
=> Show version of `1build`

docs/CHANGELOG.md
Issue: #89
- Introduce changelog draft for next releases
=> Add changelog draft

.travis.yml, docs/CHANGELOG.md
Issue: #98
- [] I have update README (If needed)
=> Travis CI use py3 for running tests on all os

docs/CHANGELOG.md, onebuild/__init__.py, tests/test_version_command.py
Issue: #105
- document release in changelog
=> Release 1.1.0

onebuild/__init__.py
=> release 1.1.1

tests/test_version_command.py
=> release 1.1.1 test fix

README.md, docs/CHANGELOG.md
Add slack join button to readme
=> Add slack join button to readme

.github/auto-comment.yml
=> Auto comment bot

ci-reporter.yml
=> Auto releaser

docs/CHANGELOG.md
=> Update version in change-log draft

.github/pull_request_template.md, .github/release-drafter.yml, docs/CHANGELOG.md
=> Add contributors in release drafter

cmd/exec/exec.go, cmd/utils/utils.go, testing/fixtures/execute_cmd_fixtures.go
Found a few typos while looking through the source code. 
- Fixes typos
N.A
=> Fix typo errors

README.md
Then please list all decencies introduced in this PR if any with reason.
-   Dependency A - Reason
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have update README (If needed)
=> Contributors list to readme

cmd/exec/exec.go
support interactive commands
N/A
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] I have update README (If needed)
=> Support interactive commands
